"""Add is_verified field to users

Revision ID: 2d0984f9d41c
Revises: 7448cbb98b28
Create Date: 2024-11-18 18:03:08.735528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0984f9d41c'
down_revision: Union[str, None] = '7448cbb98b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'uploaded_role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_ops_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_ops_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_verified')
    op.alter_column('files', 'uploaded_role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
